import "@styles/globals.scss";
import { Inter, Roboto_Flex } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--inter-font" });
const robotoflex = Roboto_Flex({
  subsets: ["latin"],
  variable: "--roboto-flex-font"
});

const fontAwesome = {
  href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
  rel: "stylesheet",
  variable: "--font-awesome"
};
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${robotoflex.variable} ${fontAwesome.variable}`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
